spring.application.name=PfeBack

# --- MongoDB Atlas ---
spring.data.mongodb.uri=mongodb+srv://nourelhoudakafsi_db_user:RRS4e76yO4jmGR0e@mejd.kvbkpli.mongodb.net/pfe?retryWrites=true&w=majority&appName=Mejd
spring.data.mongodb.auto-index-creation=true

# --- Server ---
server.port=8080
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false

# --- JPA (you don't need Hibernate/MySQL for MongoDB, but I leave it if you use MySQL elsewhere)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true

# --- Email ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=majdikadida2017@gmail.com
spring.mail.password=vqix sbnf yvoa didj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always